src/Entity/Chambre.php
<?php

namespace App\Entity;

use App\Repository\ChambreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ChambreRepository::class)]
class Chambre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $titre = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description_courte = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description_longue = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $create_at = null;

    #[ORM\OneToMany(mappedBy: 'chambre', targetEntity: Photo::class)]
    private Collection $photos;

    #[ORM\Column(nullable: true)]
    private ?float $prixJournalier = null;

    public function __construct()
    {
        $this->photos = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(?string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescriptionCourte(): ?string
    {
        return $this->description_courte;
    }

    public function setDescriptionCourte(?string $description_courte): static
    {
        $this->description_courte = $description_courte;

        return $this;
    }

    public function getDescriptionLongue(): ?string
    {
        return $this->description_longue;
    }

    public function setDescriptionLongue(?string $description_longue): static
    {
        $this->description_longue = $description_longue;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeImmutable
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeImmutable $create_at): static
    {
        $this->create_at = $create_at;

        return $this;
    }

    /**
     * @return Collection<int, Photo>
     */
    public function getPhotos(): Collection
    {
        return $this->photos;
    }

    public function addPhoto(Photo $photo): static
    {
        if (!$this->photos->contains($photo)) {
            $this->photos->add($photo);
            $photo->setChambre($this);
        }

        return $this;
    }

    public function removePhoto(Photo $photo): static
    {
        if ($this->photos->removeElement($photo)) {
            // set the owning side to null (unless already changed)
            if ($photo->getChambre() === $this) {
                $photo->setChambre(null);
            }
        }

        return $this;
    }

    public function getPrixJournalier(): ?float
    {
        return $this->prixJournalier;
    }

    public function setPrixJournalier(?float $prixJournalier): static
    {
        $this->prixJournalier = $prixJournalier;

        return $this;
    }
}

src/Form/ChambreType.php
<?php

namespace App\Form;

use App\Entity\Chambre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class ChambreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('description_courte')
            ->add('description_longue')
            ->add('prixJournalier')
            // ->add('create_at')
            ->add('photo', FileType::class, [
                'multiple' => true,
                'mapped' => false,
                'required' => false
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Chambre::class,
        ]);
    }
}

src/Controller/ChambreController.php
<?php

namespace App\Controller;

use App\Entity\Photo;
use DateTimeImmutable;
use App\Entity\Chambre;
use App\Entity\User;
use App\Form\ChambreType;
use App\Repository\ChambreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/chambre')]
class ChambreController extends AbstractController
{
    #[Route('/', name: 'app_chambre_index', methods: ['GET'])]
    public function index(ChambreRepository $chambreRepository,): Response
    {
        if ($this->getUser()) {
            if ($this->getUser()->getRoles() == ["ROLE_USER", "ROLE_ADMIN"]) {
                return $this->render('chambre/index.html.twig', [
                    'chambres' => $chambreRepository->findAll(),
                ]);
            }
        }


        return $this->render('chambre/indexUser.html.twig', [
            'chambres' => $chambreRepository->findAll(),
        ]);
    }




    #[Route('/new', name: 'app_chambre_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {



        $chambre = new Chambre();
        $form = $this->createForm(ChambreType::class, $chambre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $photos = $form->get('photo')->getData();
            foreach ($photos as $photo) {

                $nomFichier = uniqid() . '.' . $photo->guessExtension();

                $photo->move('images/Chambres', $nomFichier);

                $photo = new Photo();
                $photo->setReference($nomFichier);
                $chambre->addPhoto($photo);

                $entityManager->persist($photo);
            }
            $chambre->setCreateAt(new DateTimeImmutable());
            $entityManager->persist($chambre);
            $entityManager->flush();

            return $this->redirectToRoute('app_chambre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('chambre/new.html.twig', [
            'chambre' => $chambre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_chambre_show', methods: ['GET'])]
    public function show(Chambre $chambre): Response
    {
        return $this->render('chambre/show.html.twig', [
            'chambre' => $chambre,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_chambre_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Chambre $chambre, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ChambreType::class, $chambre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_chambre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('chambre/edit.html.twig', [
            'chambre' => $chambre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_chambre_delete', methods: ['POST'])]
    public function delete(Request $request, Chambre $chambre, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $chambre->getId(), $request->request->get('_token'))) {
            $entityManager->remove($chambre);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_chambre_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/chambre/_delete_form.html.twig
<form method="post" action="{{ path('app_chambre_delete', {'id': chambre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ chambre.id) }}">
    <button class="btn">Delete</button>
</form>

templates/chambre/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
<button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/chambre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Chambre{% endblock %}

{% block body %}
    <h1>Edit Chambre</h1>

    {{ include('chambre/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_chambre_index') }}">back to list</a>

    {{ include('chambre/_delete_form.html.twig') }}
{% endblock %}

templates/chambre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Chambre index
{% endblock %}

{% block body %}
	<br><br><br>
	<h1 class="text-center">Chambres</h1>

	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Titre</th>
				<th>Description_courte</th>
				<th>Description_longue</th>
				<th>Prix journalier</th>
				<th>Photo</th>
				<th>actions</th>
			</tr>
		</thead>
		<tbody>
			{% for chambre in chambres %}
				<tr>
					<td>{{ chambre.id }}</td>
					<td>{{ chambre.titre }}</td>
					<td>{{ chambre.descriptionCourte }}</td>
					<td>{{ chambre.descriptionLongue }}</td>
					<td>{{ chambre.prixJournalier }}</td>
					{# <td>{{ chambre.createAt ? chambre.createAt|date('Y-m-d H:i:s') : '' }}</td> #}
					<td>
						{% for photo in chambre.photos %}
							<img src="{{asset('images/Chambres/'~ photo.reference)}}" alt="" style='width:30%'>
						{% endfor %}
					</td>
					<td>
						<a href="{{ path('app_chambre_show', {'id': chambre.id}) }}" class="btn btn-success">show</a><br><br>
						<a href="{{ path('app_chambre_edit', {'id': chambre.id}) }}" class="btn btn-warning">edit</a>
						<br><br>
						<a href="{{ path('app_dateChoice', {'id': chambre.id}) }}" class="btn btn-dark">Reserver</a>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="6">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

	<a href="{{ path('app_chambre_new') }}" class="btn btn-info">Create new</a>
{% endblock %}

templates/chambre/indexUser.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HomeController!
{% endblock %}

{% block body %}
	<div class="chambres">
		{% for chambre in chambres %}

			<div class="card" style="width: 18rem;">
				{% for photo in chambre.photos %}
					<img src="{{asset('images/Chambres/'~ photo.reference)}}" class="card-img-top" alt="...">
				{% endfor %}
				<div class="card-body text-center">
					<h5 class="card-title">{{ chambre.titre }}</h5>
					<p class="card-text">{{ chambre.descriptionCourte }}</p>
					<p class="card-text">{{ chambre.prixJournalier }}</p>
					<a href="{{ path('app_chambre_show', {'id': chambre.id}) }}" class="btn btn-primary">Voir</a>
				</div>
			</div>

		{% endfor %}

	</div>
{% endblock %}

templates/chambre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Chambre
{% endblock %}

{% block body %}
	<div class="container mt-5  p-5">

		<h1>Create new Chambre</h1>

		{{ include('chambre/_form.html.twig') }}


		<a href="{{ path('app_chambre_index') }}">back to list</a>
	</div>
{% endblock %}

templates/chambre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Chambre
{% endblock %}

{% block body %}

	<br><br>
	<div class="showChambre">
		<h1>{{ chambre.titre }}</h1>
		<br><br>
		{% for photo in chambre.photos %}
			<img src="{{asset('images/Chambres/'~ photo.reference)}}" alt="" style='width:60%'>
		{% endfor %}
		<br><br>
		<h2>Description courte :
			{{ chambre.descriptionCourte }}</h2>

		<br>


		<h2>Description long:
			{{ chambre.descriptionLongue}}</h2>
		<br>
		<h2>Prix journalier
			{{ chambre.prixJournalier}}€/nuit</h2>
		<br>
		<a href="{{ path('app_dateChoice', {'id': chambre.id}) }}" class="btn btn-dark">Reserver</a>
	</div>
	{# 
																																					    <table class="table">
																																					        <tbody>
																																					            <tr>
																																					                <th>Id</th>
																																					                <td>{{ chambre.id }}</td>
																																					            </tr>
																																					            <tr>
																																					                <th>Titre</th>
																																					                <td>{{ chambre.titre }}</td>
																																					            </tr>
																																					            <tr>
																																					                <th>Description_courte</th>
																																					                <td>{{ chambre.descriptionCourte }}</td>
																																					            </tr>
																																					            <tr>
																																					                <th>Description_longue</th>
																																					                <td>{{ chambre.descriptionLongue }}</td>
																																					            </tr>
																																					            <tr>
																																					                <th>Create_at</th>
																																					                <td>{{ chambre.createAt ? chambre.createAt|date('Y-m-d H:i:s') : '' }}</td>
																																					            </tr>
																																					        </tbody>
																																					    </table>
																																					
																																					    <a href="{{ path('app_chambre_index') }}">back to list</a>
																																					
																																					    <a href="{{ path('app_chambre_edit', {'id': chambre.id}) }}">edit</a> #}

	{# {{ include('chambre/_delete_form.html.twig') }} #}
{% endblock %}